#ifndef _MEM_ORG
#define _MEM_ORG

#define MEM_INIT_BASIC_BLOCK 65
#define MEM_OS_STARTUP_CODE 1
#define MEM_EX_HANDLER 2
#define MEM_INT1 4
#define MEM_TIMERINT 4
#define MEM_DISKCONTROLLER_INT 6
#define MEM_CONSOLE_INT 8
#define MEM_MOD0 40
#define MEM_INIT_PAGE 65
#define MEM_LIBRARY_PAGE 63
#define MEM_INT_SIZE 2
#define MEM_MOD_SIZE 2
#define PAGE_SIZE 512

#endif